// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientsvc.proto

package clientsvc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewClientRequest struct {
	Address              string                               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SubInfos             map[string]*NewClientRequest_SubInfo `protobuf:"bytes,2,rep,name=sub_infos,json=subInfos,proto3" json:"sub_infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *NewClientRequest) Reset()         { *m = NewClientRequest{} }
func (m *NewClientRequest) String() string { return proto.CompactTextString(m) }
func (*NewClientRequest) ProtoMessage()    {}
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{0}
}

func (m *NewClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientRequest.Unmarshal(m, b)
}
func (m *NewClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientRequest.Marshal(b, m, deterministic)
}
func (m *NewClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientRequest.Merge(m, src)
}
func (m *NewClientRequest) XXX_Size() int {
	return xxx_messageInfo_NewClientRequest.Size(m)
}
func (m *NewClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientRequest proto.InternalMessageInfo

func (m *NewClientRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewClientRequest) GetSubInfos() map[string]*NewClientRequest_SubInfo {
	if m != nil {
		return m.SubInfos
	}
	return nil
}

type NewClientRequest_SubInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientRequest_SubInfo) Reset()         { *m = NewClientRequest_SubInfo{} }
func (m *NewClientRequest_SubInfo) String() string { return proto.CompactTextString(m) }
func (*NewClientRequest_SubInfo) ProtoMessage()    {}
func (*NewClientRequest_SubInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{0, 0}
}

func (m *NewClientRequest_SubInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientRequest_SubInfo.Unmarshal(m, b)
}
func (m *NewClientRequest_SubInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientRequest_SubInfo.Marshal(b, m, deterministic)
}
func (m *NewClientRequest_SubInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientRequest_SubInfo.Merge(m, src)
}
func (m *NewClientRequest_SubInfo) XXX_Size() int {
	return xxx_messageInfo_NewClientRequest_SubInfo.Size(m)
}
func (m *NewClientRequest_SubInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientRequest_SubInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientRequest_SubInfo proto.InternalMessageInfo

func (m *NewClientRequest_SubInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewClientRequest_SubInfo) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type NewClientResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientResponse) Reset()         { *m = NewClientResponse{} }
func (m *NewClientResponse) String() string { return proto.CompactTextString(m) }
func (*NewClientResponse) ProtoMessage()    {}
func (*NewClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{1}
}

func (m *NewClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientResponse.Unmarshal(m, b)
}
func (m *NewClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientResponse.Marshal(b, m, deterministic)
}
func (m *NewClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientResponse.Merge(m, src)
}
func (m *NewClientResponse) XXX_Size() int {
	return xxx_messageInfo_NewClientResponse.Size(m)
}
func (m *NewClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientResponse proto.InternalMessageInfo

func (m *NewClientResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UnregisterClientRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterClientRequest) Reset()         { *m = UnregisterClientRequest{} }
func (m *UnregisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterClientRequest) ProtoMessage()    {}
func (*UnregisterClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{2}
}

func (m *UnregisterClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterClientRequest.Unmarshal(m, b)
}
func (m *UnregisterClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterClientRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterClientRequest.Merge(m, src)
}
func (m *UnregisterClientRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterClientRequest.Size(m)
}
func (m *UnregisterClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterClientRequest proto.InternalMessageInfo

func (m *UnregisterClientRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UnregisterClientResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterClientResponse) Reset()         { *m = UnregisterClientResponse{} }
func (m *UnregisterClientResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterClientResponse) ProtoMessage()    {}
func (*UnregisterClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{3}
}

func (m *UnregisterClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterClientResponse.Unmarshal(m, b)
}
func (m *UnregisterClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterClientResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterClientResponse.Merge(m, src)
}
func (m *UnregisterClientResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterClientResponse.Size(m)
}
func (m *UnregisterClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterClientResponse proto.InternalMessageInfo

func (m *UnregisterClientResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type NewTransactionsRequest struct {
	Client               string                                          `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Transactions         map[string]*NewTransactionsRequest_Transactions `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *NewTransactionsRequest) Reset()         { *m = NewTransactionsRequest{} }
func (m *NewTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*NewTransactionsRequest) ProtoMessage()    {}
func (*NewTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{4}
}

func (m *NewTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionsRequest.Unmarshal(m, b)
}
func (m *NewTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *NewTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionsRequest.Merge(m, src)
}
func (m *NewTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_NewTransactionsRequest.Size(m)
}
func (m *NewTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionsRequest proto.InternalMessageInfo

func (m *NewTransactionsRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *NewTransactionsRequest) GetTransactions() map[string]*NewTransactionsRequest_Transactions {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type NewTransactionsRequest_Transaction struct {
	RawTransaction       []byte   `protobuf:"bytes,1,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTransactionsRequest_Transaction) Reset()         { *m = NewTransactionsRequest_Transaction{} }
func (m *NewTransactionsRequest_Transaction) String() string { return proto.CompactTextString(m) }
func (*NewTransactionsRequest_Transaction) ProtoMessage()    {}
func (*NewTransactionsRequest_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{4, 0}
}

func (m *NewTransactionsRequest_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionsRequest_Transaction.Unmarshal(m, b)
}
func (m *NewTransactionsRequest_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionsRequest_Transaction.Marshal(b, m, deterministic)
}
func (m *NewTransactionsRequest_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionsRequest_Transaction.Merge(m, src)
}
func (m *NewTransactionsRequest_Transaction) XXX_Size() int {
	return xxx_messageInfo_NewTransactionsRequest_Transaction.Size(m)
}
func (m *NewTransactionsRequest_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionsRequest_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionsRequest_Transaction proto.InternalMessageInfo

func (m *NewTransactionsRequest_Transaction) GetRawTransaction() []byte {
	if m != nil {
		return m.RawTransaction
	}
	return nil
}

func (m *NewTransactionsRequest_Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *NewTransactionsRequest_Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type NewTransactionsRequest_Transactions struct {
	List                 []*NewTransactionsRequest_Transaction `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *NewTransactionsRequest_Transactions) Reset()         { *m = NewTransactionsRequest_Transactions{} }
func (m *NewTransactionsRequest_Transactions) String() string { return proto.CompactTextString(m) }
func (*NewTransactionsRequest_Transactions) ProtoMessage()    {}
func (*NewTransactionsRequest_Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{4, 1}
}

func (m *NewTransactionsRequest_Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionsRequest_Transactions.Unmarshal(m, b)
}
func (m *NewTransactionsRequest_Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionsRequest_Transactions.Marshal(b, m, deterministic)
}
func (m *NewTransactionsRequest_Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionsRequest_Transactions.Merge(m, src)
}
func (m *NewTransactionsRequest_Transactions) XXX_Size() int {
	return xxx_messageInfo_NewTransactionsRequest_Transactions.Size(m)
}
func (m *NewTransactionsRequest_Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionsRequest_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionsRequest_Transactions proto.InternalMessageInfo

func (m *NewTransactionsRequest_Transactions) GetList() []*NewTransactionsRequest_Transaction {
	if m != nil {
		return m.List
	}
	return nil
}

type NewTransactionsResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTransactionsResponse) Reset()         { *m = NewTransactionsResponse{} }
func (m *NewTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*NewTransactionsResponse) ProtoMessage()    {}
func (*NewTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35be3a4f9f0765b, []int{5}
}

func (m *NewTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransactionsResponse.Unmarshal(m, b)
}
func (m *NewTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *NewTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransactionsResponse.Merge(m, src)
}
func (m *NewTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_NewTransactionsResponse.Size(m)
}
func (m *NewTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransactionsResponse proto.InternalMessageInfo

func (m *NewTransactionsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*NewClientRequest)(nil), "NewClientRequest")
	proto.RegisterMapType((map[string]*NewClientRequest_SubInfo)(nil), "NewClientRequest.SubInfosEntry")
	proto.RegisterType((*NewClientRequest_SubInfo)(nil), "NewClientRequest.SubInfo")
	proto.RegisterType((*NewClientResponse)(nil), "NewClientResponse")
	proto.RegisterType((*UnregisterClientRequest)(nil), "UnregisterClientRequest")
	proto.RegisterType((*UnregisterClientResponse)(nil), "UnregisterClientResponse")
	proto.RegisterType((*NewTransactionsRequest)(nil), "NewTransactionsRequest")
	proto.RegisterMapType((map[string]*NewTransactionsRequest_Transactions)(nil), "NewTransactionsRequest.TransactionsEntry")
	proto.RegisterType((*NewTransactionsRequest_Transaction)(nil), "NewTransactionsRequest.Transaction")
	proto.RegisterType((*NewTransactionsRequest_Transactions)(nil), "NewTransactionsRequest.Transactions")
	proto.RegisterType((*NewTransactionsResponse)(nil), "NewTransactionsResponse")
}

func init() {
	proto.RegisterFile("clientsvc.proto", fileDescriptor_c35be3a4f9f0765b)
}

var fileDescriptor_c35be3a4f9f0765b = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0x36, 0xa5, 0x93, 0xb4, 0x89, 0x47, 0x28, 0xd9, 0xee, 0x85, 0xc8, 0x20, 0x11,
	0x84, 0xb4, 0x08, 0xe7, 0x00, 0xaa, 0x7a, 0x43, 0x80, 0x7a, 0xa0, 0x87, 0x2d, 0x70, 0xe0, 0x52,
	0x6d, 0xdc, 0x85, 0x5a, 0x44, 0x76, 0xd8, 0x5d, 0x27, 0xca, 0x37, 0xf0, 0x93, 0xfc, 0x05, 0x57,
	0x64, 0x7b, 0x8b, 0x36, 0x71, 0x0c, 0xb9, 0xed, 0x8c, 0xe7, 0xcd, 0xcc, 0x9b, 0xf7, 0x64, 0xe8,
	0xc7, 0xf3, 0x44, 0xa6, 0x46, 0x2f, 0x63, 0xb6, 0x50, 0x99, 0xc9, 0xc2, 0xdf, 0x1e, 0x0c, 0xae,
	0xe4, 0xea, 0x4d, 0x99, 0xe6, 0xf2, 0x47, 0x2e, 0xb5, 0x41, 0x02, 0x47, 0xe2, 0xf6, 0x56, 0x49,
	0xad, 0x89, 0x37, 0xf6, 0x26, 0xc7, 0xfc, 0x3e, 0xc4, 0x0b, 0x38, 0xd6, 0xf9, 0xec, 0x26, 0x49,
	0xbf, 0x66, 0x9a, 0xf8, 0xe3, 0xf6, 0xa4, 0x1b, 0x3d, 0x62, 0xdb, 0x78, 0x76, 0x9d, 0xcf, 0x2e,
	0x8b, 0x8a, 0xb7, 0xa9, 0x51, 0x6b, 0xfe, 0x40, 0xdb, 0x90, 0x4e, 0xe1, 0xc8, 0x7e, 0x42, 0x84,
	0x03, 0xb3, 0x5e, 0x48, 0xdb, 0xbf, 0x7c, 0xe3, 0x43, 0x38, 0x5c, 0x8a, 0x79, 0x2e, 0x89, 0x3f,
	0xf6, 0x26, 0x3d, 0x5e, 0x05, 0xf4, 0x33, 0x9c, 0x6c, 0xf4, 0xc3, 0x01, 0xb4, 0xbf, 0xcb, 0xb5,
	0x45, 0x16, 0x4f, 0x7c, 0xe1, 0x02, 0xbb, 0xd1, 0x59, 0xe3, 0x46, 0xb6, 0xe7, 0xb9, 0xff, 0xda,
	0x0b, 0x9f, 0x43, 0xe0, 0x94, 0xe9, 0x45, 0x96, 0x6a, 0x89, 0x43, 0xe8, 0x68, 0x23, 0x4c, 0x5e,
	0x11, 0x3f, 0xe4, 0x36, 0x0a, 0xa7, 0x30, 0xfa, 0x94, 0x2a, 0xf9, 0x2d, 0xd1, 0x46, 0xaa, 0x3d,
	0x8f, 0x15, 0x46, 0x40, 0xea, 0xa0, 0xff, 0x0c, 0xfa, 0xd9, 0x86, 0xe1, 0x95, 0x5c, 0x7d, 0x54,
	0x22, 0xd5, 0x22, 0x36, 0x49, 0x96, 0xea, 0xfb, 0x41, 0x43, 0xe8, 0x54, 0xea, 0xd9, 0x39, 0x36,
	0xc2, 0x0f, 0xd0, 0x33, 0x4e, 0xb9, 0x95, 0xe5, 0x19, 0xdb, 0xdd, 0x86, 0xb9, 0xb9, 0x4a, 0xa0,
	0x0d, 0x38, 0xfd, 0x02, 0x5d, 0xa7, 0x04, 0x9f, 0x42, 0x5f, 0x89, 0xd5, 0x8d, 0x53, 0x52, 0x8e,
	0xef, 0xf1, 0x53, 0x25, 0xdc, 0xfe, 0x85, 0xa2, 0x77, 0x42, 0xdf, 0x59, 0xf1, 0xca, 0x37, 0x9e,
	0x82, 0x6f, 0x32, 0xd2, 0x2e, 0x33, 0xbe, 0xc9, 0xe8, 0x7b, 0xe8, 0xb9, 0xe3, 0xf1, 0x15, 0x1c,
	0xcc, 0x13, 0x5d, 0x10, 0x2a, 0x56, 0x7e, 0xbc, 0xc7, 0xca, 0xbc, 0x04, 0x50, 0x09, 0x41, 0x8d,
	0xc7, 0x0e, 0x63, 0x9c, 0x6f, 0x1a, 0xe3, 0xc9, 0x3e, 0x37, 0x71, 0x3d, 0xf2, 0x12, 0x46, 0x35,
	0xc4, 0xbf, 0x05, 0x8c, 0x7e, 0x79, 0x70, 0x52, 0x69, 0x7d, 0x2d, 0xd5, 0x32, 0x89, 0x25, 0x5e,
	0x40, 0xc0, 0xad, 0x09, 0xfe, 0x1a, 0x0e, 0x83, 0x9a, 0x47, 0x29, 0xb2, 0x9a, 0x1f, 0xc3, 0x16,
	0x5e, 0xc2, 0x60, 0xdb, 0x44, 0x48, 0x58, 0x83, 0x19, 0xe9, 0x19, 0x6b, 0x72, 0x5c, 0xd8, 0xc2,
	0x77, 0xd0, 0xdf, 0x62, 0x83, 0xa3, 0x86, 0x8b, 0x50, 0xc2, 0x1a, 0x88, 0x87, 0xad, 0x59, 0xa7,
	0xfc, 0x75, 0x4c, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x90, 0xe5, 0x5d, 0x4d, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	RegisterNewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error)
	UnregisterClient(ctx context.Context, in *UnregisterClientRequest, opts ...grpc.CallOption) (*UnregisterClientResponse, error)
	NewTransactions(ctx context.Context, in *NewTransactionsRequest, opts ...grpc.CallOption) (*NewTransactionsResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) RegisterNewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error) {
	out := new(NewClientResponse)
	err := c.cc.Invoke(ctx, "/ClientService/RegisterNewClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UnregisterClient(ctx context.Context, in *UnregisterClientRequest, opts ...grpc.CallOption) (*UnregisterClientResponse, error) {
	out := new(UnregisterClientResponse)
	err := c.cc.Invoke(ctx, "/ClientService/UnregisterClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) NewTransactions(ctx context.Context, in *NewTransactionsRequest, opts ...grpc.CallOption) (*NewTransactionsResponse, error) {
	out := new(NewTransactionsResponse)
	err := c.cc.Invoke(ctx, "/ClientService/NewTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	RegisterNewClient(context.Context, *NewClientRequest) (*NewClientResponse, error)
	UnregisterClient(context.Context, *UnregisterClientRequest) (*UnregisterClientResponse, error)
	NewTransactions(context.Context, *NewTransactionsRequest) (*NewTransactionsResponse, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) RegisterNewClient(ctx context.Context, req *NewClientRequest) (*NewClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewClient not implemented")
}
func (*UnimplementedClientServiceServer) UnregisterClient(ctx context.Context, req *UnregisterClientRequest) (*UnregisterClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterClient not implemented")
}
func (*UnimplementedClientServiceServer) NewTransactions(ctx context.Context, req *NewTransactionsRequest) (*NewTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTransactions not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_RegisterNewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).RegisterNewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientService/RegisterNewClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).RegisterNewClient(ctx, req.(*NewClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UnregisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UnregisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientService/UnregisterClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UnregisterClient(ctx, req.(*UnregisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_NewTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).NewTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientService/NewTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).NewTransactions(ctx, req.(*NewTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewClient",
			Handler:    _ClientService_RegisterNewClient_Handler,
		},
		{
			MethodName: "UnregisterClient",
			Handler:    _ClientService_UnregisterClient_Handler,
		},
		{
			MethodName: "NewTransactions",
			Handler:    _ClientService_NewTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientsvc.proto",
}
