// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dappcontainer.proto

package dappcontainer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Receipt struct {
	Txhash               []byte         `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	ContractAddress      []byte         `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Status               uint64         `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Logs                 []*Receipt_Log `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_21dcf219e974a8d7, []int{0}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *Receipt) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *Receipt) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Receipt) GetLogs() []*Receipt_Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Receipt_Log struct {
	Topics               [][]byte `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Address              []byte   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt_Log) Reset()         { *m = Receipt_Log{} }
func (m *Receipt_Log) String() string { return proto.CompactTextString(m) }
func (*Receipt_Log) ProtoMessage()    {}
func (*Receipt_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_21dcf219e974a8d7, []int{0, 0}
}

func (m *Receipt_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt_Log.Unmarshal(m, b)
}
func (m *Receipt_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt_Log.Marshal(b, m, deterministic)
}
func (m *Receipt_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt_Log.Merge(m, src)
}
func (m *Receipt_Log) XXX_Size() int {
	return xxx_messageInfo_Receipt_Log.Size(m)
}
func (m *Receipt_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt_Log proto.InternalMessageInfo

func (m *Receipt_Log) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Receipt_Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Receipt_Log) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type NewReceiptsResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewReceiptsResponse) Reset()         { *m = NewReceiptsResponse{} }
func (m *NewReceiptsResponse) String() string { return proto.CompactTextString(m) }
func (*NewReceiptsResponse) ProtoMessage()    {}
func (*NewReceiptsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21dcf219e974a8d7, []int{1}
}

func (m *NewReceiptsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewReceiptsResponse.Unmarshal(m, b)
}
func (m *NewReceiptsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewReceiptsResponse.Marshal(b, m, deterministic)
}
func (m *NewReceiptsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewReceiptsResponse.Merge(m, src)
}
func (m *NewReceiptsResponse) XXX_Size() int {
	return xxx_messageInfo_NewReceiptsResponse.Size(m)
}
func (m *NewReceiptsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewReceiptsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewReceiptsResponse proto.InternalMessageInfo

func (m *NewReceiptsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Receipt)(nil), "Receipt")
	proto.RegisterType((*Receipt_Log)(nil), "Receipt.Log")
	proto.RegisterType((*NewReceiptsResponse)(nil), "NewReceiptsResponse")
}

func init() {
	proto.RegisterFile("dappcontainer.proto", fileDescriptor_21dcf219e974a8d7)
}

var fileDescriptor_21dcf219e974a8d7 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0xa9, 0xbb, 0x32, 0xbb, 0xa2, 0x64, 0x45, 0xc2, 0x9e, 0x42, 0x4f, 0xf5, 0x60,
	0xc1, 0xf5, 0x09, 0x56, 0xbd, 0xb9, 0x78, 0xc8, 0x0b, 0x48, 0x6c, 0x43, 0xb7, 0x20, 0x4d, 0xe8,
	0x8c, 0xe8, 0x7b, 0xfa, 0x42, 0xd2, 0x31, 0x81, 0x1e, 0xbc, 0xe5, 0xff, 0x93, 0x99, 0xff, 0xcb,
	0x0f, 0x9b, 0xd6, 0xc5, 0xd8, 0x84, 0x81, 0x5c, 0x3f, 0xf8, 0xb1, 0x8e, 0x63, 0xa0, 0x50, 0xfe,
	0x08, 0x58, 0x5a, 0xdf, 0xf8, 0x3e, 0x92, 0xba, 0x81, 0x05, 0x7d, 0x1f, 0x1d, 0x1e, 0xb5, 0x30,
	0xa2, 0x5a, 0xdb, 0xa4, 0xd4, 0x2d, 0x5c, 0x4d, 0x63, 0xa3, 0x6b, 0xe8, 0xcd, 0xb5, 0xed, 0xe8,
	0x11, 0xf5, 0x29, 0xbf, 0xb8, 0xcc, 0xfe, 0xfe, 0xcf, 0x9e, 0x56, 0x20, 0x39, 0xfa, 0x44, 0x2d,
	0x8d, 0xa8, 0x0a, 0x9b, 0x94, 0x32, 0x50, 0x7c, 0x84, 0x0e, 0x75, 0x61, 0x64, 0xb5, 0xda, 0xad,
	0xeb, 0x14, 0x59, 0x1f, 0x42, 0x67, 0xf9, 0x66, 0xfb, 0x02, 0xf2, 0x10, 0x3a, 0x66, 0x08, 0xb1,
	0x6f, 0x50, 0x0b, 0x23, 0x99, 0x81, 0x95, 0x52, 0x50, 0xb4, 0x8e, 0x5c, 0xca, 0xe5, 0xb3, 0xd2,
	0xb0, 0xcc, 0x38, 0x92, 0xed, 0x2c, 0xcb, 0x3b, 0xd8, 0xbc, 0xfa, 0xaf, 0x14, 0x82, 0xd6, 0x63,
	0x0c, 0x03, 0xfa, 0x19, 0xdd, 0xf4, 0xc1, 0xb3, 0x4c, 0xb7, 0x7b, 0x84, 0x8b, 0xe7, 0x7d, 0x8c,
	0x4f, 0xb9, 0x1b, 0x75, 0x0f, 0xab, 0xd9, 0xbc, 0x3a, 0xcf, 0xbc, 0xdb, 0xeb, 0xfa, 0x9f, 0xbd,
	0xe5, 0x49, 0x25, 0xde, 0x17, 0xdc, 0xe7, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xf8,
	0x59, 0xca, 0x66, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DAppContainerClient is the client API for DAppContainer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAppContainerClient interface {
	NewReceipts(ctx context.Context, opts ...grpc.CallOption) (DAppContainer_NewReceiptsClient, error)
}

type dAppContainerClient struct {
	cc grpc.ClientConnInterface
}

func NewDAppContainerClient(cc grpc.ClientConnInterface) DAppContainerClient {
	return &dAppContainerClient{cc}
}

func (c *dAppContainerClient) NewReceipts(ctx context.Context, opts ...grpc.CallOption) (DAppContainer_NewReceiptsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DAppContainer_serviceDesc.Streams[0], "/DAppContainer/NewReceipts", opts...)
	if err != nil {
		return nil, err
	}
	x := &dAppContainerNewReceiptsClient{stream}
	return x, nil
}

type DAppContainer_NewReceiptsClient interface {
	Send(*Receipt) error
	CloseAndRecv() (*NewReceiptsResponse, error)
	grpc.ClientStream
}

type dAppContainerNewReceiptsClient struct {
	grpc.ClientStream
}

func (x *dAppContainerNewReceiptsClient) Send(m *Receipt) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dAppContainerNewReceiptsClient) CloseAndRecv() (*NewReceiptsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NewReceiptsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DAppContainerServer is the server API for DAppContainer service.
type DAppContainerServer interface {
	NewReceipts(DAppContainer_NewReceiptsServer) error
}

// UnimplementedDAppContainerServer can be embedded to have forward compatible implementations.
type UnimplementedDAppContainerServer struct {
}

func (*UnimplementedDAppContainerServer) NewReceipts(srv DAppContainer_NewReceiptsServer) error {
	return status.Errorf(codes.Unimplemented, "method NewReceipts not implemented")
}

func RegisterDAppContainerServer(s *grpc.Server, srv DAppContainerServer) {
	s.RegisterService(&_DAppContainer_serviceDesc, srv)
}

func _DAppContainer_NewReceipts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DAppContainerServer).NewReceipts(&dAppContainerNewReceiptsServer{stream})
}

type DAppContainer_NewReceiptsServer interface {
	SendAndClose(*NewReceiptsResponse) error
	Recv() (*Receipt, error)
	grpc.ServerStream
}

type dAppContainerNewReceiptsServer struct {
	grpc.ServerStream
}

func (x *dAppContainerNewReceiptsServer) SendAndClose(m *NewReceiptsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dAppContainerNewReceiptsServer) Recv() (*Receipt, error) {
	m := new(Receipt)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DAppContainer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DAppContainer",
	HandlerType: (*DAppContainerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewReceipts",
			Handler:       _DAppContainer_NewReceipts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dappcontainer.proto",
}
